//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public enum AIState {
  IsAlive = 0x01,
  CanUseLegs = 0x02,
  CanUseHands = 0x04,
  CanUseMouth = 0x08,
  CanUseEars = 0x10,
  CanUseEyes = 0x20,
  CanUseMind = 0x40,
  IsAbleToGoHostile = 0x80
}

}
