//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public class CExoArrayListCGameEffectPtr : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CExoArrayListCGameEffectPtr(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CExoArrayListCGameEffectPtr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CExoArrayListCGameEffectPtr() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NWNXLibPINVOKE.delete_CExoArrayListCGameEffectPtr(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_p_CGameEffect element {
    set {
      NWNXLibPINVOKE.CExoArrayListCGameEffectPtr_element_set(swigCPtr, SWIGTYPE_p_p_CGameEffect.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = NWNXLibPINVOKE.CExoArrayListCGameEffectPtr_element_get(swigCPtr);
      SWIGTYPE_p_p_CGameEffect ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_CGameEffect(cPtr, false);
      return ret;
    } 
  }

  public int num {
    set {
      NWNXLibPINVOKE.CExoArrayListCGameEffectPtr_num_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CExoArrayListCGameEffectPtr_num_get(swigCPtr);
      return ret;
    } 
  }

  public int array_size {
    set {
      NWNXLibPINVOKE.CExoArrayListCGameEffectPtr_array_size_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CExoArrayListCGameEffectPtr_array_size_get(swigCPtr);
      return ret;
    } 
  }

  public CExoArrayListCGameEffectPtr(int s) : this(NWNXLibPINVOKE.new_CExoArrayListCGameEffectPtr__SWIG_0(s), true) {
  }

  public CExoArrayListCGameEffectPtr() : this(NWNXLibPINVOKE.new_CExoArrayListCGameEffectPtr__SWIG_1(), true) {
  }

  public CExoArrayListCGameEffectPtr(CExoArrayListCGameEffectPtr list) : this(NWNXLibPINVOKE.new_CExoArrayListCGameEffectPtr__SWIG_2(CExoArrayListCGameEffectPtr.getCPtr(list)), true) {
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public CExoArrayListCGameEffectPtr __Assign(CExoArrayListCGameEffectPtr list) {
    CExoArrayListCGameEffectPtr ret = new CExoArrayListCGameEffectPtr(NWNXLibPINVOKE.CExoArrayListCGameEffectPtr___Assign(swigCPtr, CExoArrayListCGameEffectPtr.getCPtr(list)), false);
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_p_CGameEffect __Index(int i) {
    SWIGTYPE_p_p_CGameEffect ret = new SWIGTYPE_p_p_CGameEffect(NWNXLibPINVOKE.CExoArrayListCGameEffectPtr___Index(swigCPtr, i), false);
    return ret;
  }

  public void Allocate(int s) {
    NWNXLibPINVOKE.CExoArrayListCGameEffectPtr_Allocate(swigCPtr, s);
  }

  public void SetSize(int s) {
    NWNXLibPINVOKE.CExoArrayListCGameEffectPtr_SetSize(swigCPtr, s);
  }

  public void Pack() {
    NWNXLibPINVOKE.CExoArrayListCGameEffectPtr_Pack(swigCPtr);
  }

  public void Add(CGameEffect t) {
    NWNXLibPINVOKE.CExoArrayListCGameEffectPtr_Add(swigCPtr, CGameEffect.getCPtr(t));
  }

  public void Insert(CGameEffect t, int k) {
    NWNXLibPINVOKE.CExoArrayListCGameEffectPtr_Insert(swigCPtr, CGameEffect.getCPtr(t), k);
  }

  public void DelIndex(int i) {
    NWNXLibPINVOKE.CExoArrayListCGameEffectPtr_DelIndex(swigCPtr, i);
  }

  public SWIGTYPE_p_p_CGameEffect begin() {
    global::System.IntPtr cPtr = NWNXLibPINVOKE.CExoArrayListCGameEffectPtr_begin__SWIG_0(swigCPtr);
    SWIGTYPE_p_p_CGameEffect ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_CGameEffect(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_p_CGameEffect end() {
    global::System.IntPtr cPtr = NWNXLibPINVOKE.CExoArrayListCGameEffectPtr_end__SWIG_0(swigCPtr);
    SWIGTYPE_p_p_CGameEffect ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_CGameEffect(cPtr, false);
    return ret;
  }

}

}
