//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public unsafe class CExoArrayListCNetLayerPlayerCDKeyInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CExoArrayListCNetLayerPlayerCDKeyInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CExoArrayListCNetLayerPlayerCDKeyInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CExoArrayListCNetLayerPlayerCDKeyInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NWNXLibPINVOKE.delete_CExoArrayListCNetLayerPlayerCDKeyInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }
/*@SWIG:/__w/NWN.Native/NWN.Native/nwnx/Plugins/SWIG/SWIG_DotNET/API_NWNXLib.i,25,SWIG_DOTNET_EXTENSIONS@*/
  public global::System.IntPtr Pointer {
    get {
      return swigCPtr.Handle;
    }
  }

  public static unsafe implicit operator void*(CExoArrayListCNetLayerPlayerCDKeyInfo self) {
    return (void*)self.swigCPtr.Handle;
  }

  public static unsafe CExoArrayListCNetLayerPlayerCDKeyInfo FromPointer(void* pointer, bool memoryOwn = false) {
    return pointer != null ? new CExoArrayListCNetLayerPlayerCDKeyInfo((global::System.IntPtr)pointer, memoryOwn) : null;
  }

  public static CExoArrayListCNetLayerPlayerCDKeyInfo FromPointer(global::System.IntPtr pointer, bool memoryOwn = false) {
    return pointer != global::System.IntPtr.Zero ? new CExoArrayListCNetLayerPlayerCDKeyInfo(pointer, memoryOwn) : null;
  }

  public bool Equals(CExoArrayListCNetLayerPlayerCDKeyInfo other) {
    if (ReferenceEquals(null, other)) {
      return false;
    }

    if (ReferenceEquals(this, other)) {
      return true;
    }

    return Pointer.Equals(other.Pointer);
  }

  public override bool Equals(object obj) {
    return ReferenceEquals(this, obj) || obj is CExoArrayListCNetLayerPlayerCDKeyInfo other && Equals(other);
  }

  public override int GetHashCode() {
    return swigCPtr.Handle.GetHashCode();
  }

  public static bool operator ==(CExoArrayListCNetLayerPlayerCDKeyInfo left, CExoArrayListCNetLayerPlayerCDKeyInfo right) {
    return Equals(left, right);
  }

  public static bool operator !=(CExoArrayListCNetLayerPlayerCDKeyInfo left, CExoArrayListCNetLayerPlayerCDKeyInfo right) {
    return !Equals(left, right);
  }
/*@SWIG@*/
  public CNetLayerPlayerCDKeyInfo element {
    set {
      NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo_element_set(swigCPtr, CNetLayerPlayerCDKeyInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo_element_get(swigCPtr);
      CNetLayerPlayerCDKeyInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new CNetLayerPlayerCDKeyInfo(cPtr, false);
      return ret;
    } 
  }

  public int num {
    set {
      NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo_num_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo_num_get(swigCPtr);
      return ret;
    } 
  }

  public int array_size {
    set {
      NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo_array_size_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo_array_size_get(swigCPtr);
      return ret;
    } 
  }

  public CExoArrayListCNetLayerPlayerCDKeyInfo(int s) : this(NWNXLibPINVOKE.new_CExoArrayListCNetLayerPlayerCDKeyInfo__SWIG_0(s), true) {
  }

  public CExoArrayListCNetLayerPlayerCDKeyInfo() : this(NWNXLibPINVOKE.new_CExoArrayListCNetLayerPlayerCDKeyInfo__SWIG_1(), true) {
  }

  public CExoArrayListCNetLayerPlayerCDKeyInfo(CExoArrayListCNetLayerPlayerCDKeyInfo list) : this(NWNXLibPINVOKE.new_CExoArrayListCNetLayerPlayerCDKeyInfo__SWIG_2(CExoArrayListCNetLayerPlayerCDKeyInfo.getCPtr(list)), true) {
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public CExoArrayListCNetLayerPlayerCDKeyInfo _OpAssign(CExoArrayListCNetLayerPlayerCDKeyInfo list) {
    CExoArrayListCNetLayerPlayerCDKeyInfo ret = new CExoArrayListCNetLayerPlayerCDKeyInfo(NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo__OpAssign(swigCPtr, CExoArrayListCNetLayerPlayerCDKeyInfo.getCPtr(list)), false);
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CNetLayerPlayerCDKeyInfo _OpIndex(int i) {
    CNetLayerPlayerCDKeyInfo ret = new CNetLayerPlayerCDKeyInfo(NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo__OpIndex(swigCPtr, i), false);
    return ret;
  }

  public void Allocate(int s) {
    NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo_Allocate(swigCPtr, s);
  }

  public void SetSize(int s) {
    NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo_SetSize(swigCPtr, s);
  }

  public void Pack() {
    NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo_Pack(swigCPtr);
  }

  public void Add(CNetLayerPlayerCDKeyInfo t) {
    NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo_Add(swigCPtr, CNetLayerPlayerCDKeyInfo.getCPtr(t));
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Insert(CNetLayerPlayerCDKeyInfo t, int k) {
    NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo_Insert(swigCPtr, CNetLayerPlayerCDKeyInfo.getCPtr(t), k);
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void DelIndex(int i) {
    NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo_DelIndex(swigCPtr, i);
  }

  public CNetLayerPlayerCDKeyInfo begin() {
    global::System.IntPtr cPtr = NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo_begin(swigCPtr);
    CNetLayerPlayerCDKeyInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new CNetLayerPlayerCDKeyInfo(cPtr, false);
    return ret;
  }

  public CNetLayerPlayerCDKeyInfo end() {
    global::System.IntPtr cPtr = NWNXLibPINVOKE.CExoArrayListCNetLayerPlayerCDKeyInfo_end(swigCPtr);
    CNetLayerPlayerCDKeyInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new CNetLayerPlayerCDKeyInfo(cPtr, false);
    return ret;
  }

}

}
