//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public unsafe class CNWClassArray : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CNWClassArray(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CNWClassArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CNWClassArray() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NWNXLibPINVOKE.delete_CNWClassArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }
/*@SWIG:/__w/NWN.Native/NWN.Native/nwnx/Plugins/SWIG/SWIG_DotNET/API_NWNXLib.i,25,SWIG_DOTNET_EXTENSIONS@*/
  public global::System.IntPtr Pointer {
    get {
      return swigCPtr.Handle;
    }
  }

  public static unsafe implicit operator void*(CNWClassArray self) {
    return (void*)self.swigCPtr.Handle;
  }

  public static unsafe CNWClassArray FromPointer(void* pointer, bool memoryOwn = false) {
    return pointer != null ? new CNWClassArray((global::System.IntPtr)pointer, memoryOwn) : null;
  }

  public static CNWClassArray FromPointer(global::System.IntPtr pointer, bool memoryOwn = false) {
    return pointer != global::System.IntPtr.Zero ? new CNWClassArray(pointer, memoryOwn) : null;
  }

  public bool Equals(CNWClassArray other) {
    if (ReferenceEquals(null, other)) {
      return false;
    }

    if (ReferenceEquals(this, other)) {
      return true;
    }

    return Pointer.Equals(other.Pointer);
  }

  public override bool Equals(object obj) {
    return ReferenceEquals(this, obj) || obj is CNWClassArray other && Equals(other);
  }

  public override int GetHashCode() {
    return swigCPtr.Handle.GetHashCode();
  }

  public static bool operator ==(CNWClassArray left, CNWClassArray right) {
    return Equals(left, right);
  }

  public static bool operator !=(CNWClassArray left, CNWClassArray right) {
    return !Equals(left, right);
  }
/*@SWIG@*/

  public CNWClass this[int index] {
    get {
      return GetItem(index);
    }
    set {
      SetItem(index, value);
    }
  }
  public CNWClassArray(int nElements) : this(NWNXLibPINVOKE.new_CNWClassArray(nElements), true) {
  }

  public CNWClass GetItem(int index) {
    global::System.IntPtr cPtr = NWNXLibPINVOKE.CNWClassArray_GetItem(swigCPtr, index);
    CNWClass ret = (cPtr == global::System.IntPtr.Zero) ? null : new CNWClass(cPtr, false);
    return ret;
  }

  public void SetItem(int index, CNWClass value) {
    NWNXLibPINVOKE.CNWClassArray_SetItem(swigCPtr, index, CNWClass.getCPtr(value));
  }

  public static CNWClassArray FromPointer(CNWClass ptr) {
    global::System.IntPtr cPtr = NWNXLibPINVOKE.CNWClassArray_FromPointer(CNWClass.getCPtr(ptr));
    CNWClassArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new CNWClassArray(cPtr, false);
    return ret;
  }

}

}
