//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public class CNWDomain : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CNWDomain(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CNWDomain obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CNWDomain() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NWNXLibPINVOKE.delete_CNWDomain(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int m_nNameStrref {
    set {
      NWNXLibPINVOKE.CNWDomain_m_nNameStrref_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CNWDomain_m_nNameStrref_get(swigCPtr);
      return ret;
    } 
  }

  public int m_nDescriptionStrref {
    set {
      NWNXLibPINVOKE.CNWDomain_m_nDescriptionStrref_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CNWDomain_m_nDescriptionStrref_get(swigCPtr);
      return ret;
    } 
  }

  public CResRef m_cIcon {
    set {
      NWNXLibPINVOKE.CNWDomain_m_cIcon_set(swigCPtr, CResRef.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = NWNXLibPINVOKE.CNWDomain_m_cIcon_get(swigCPtr);
      CResRef ret = (cPtr == global::System.IntPtr.Zero) ? null : new CResRef(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_int m_lstSpells {
    set {
      NWNXLibPINVOKE.CNWDomain_m_lstSpells_set(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = NWNXLibPINVOKE.CNWDomain_m_lstSpells_get(swigCPtr);
      SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public ushort m_nGrantedFeat {
    set {
      NWNXLibPINVOKE.CNWDomain_m_nGrantedFeat_set(swigCPtr, value);
    } 
    get {
      ushort ret = NWNXLibPINVOKE.CNWDomain_m_nGrantedFeat_get(swigCPtr);
      return ret;
    } 
  }

  public int m_bValidDomain {
    set {
      NWNXLibPINVOKE.CNWDomain_m_bValidDomain_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CNWDomain_m_bValidDomain_get(swigCPtr);
      return ret;
    } 
  }

  public int m_bCastableFeat {
    set {
      NWNXLibPINVOKE.CNWDomain_m_bCastableFeat_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CNWDomain_m_bCastableFeat_get(swigCPtr);
      return ret;
    } 
  }

  public CNWDomain() : this(NWNXLibPINVOKE.new_CNWDomain(), true) {
  }

  public CExoString GetNameText() {
    CExoString ret = new CExoString(NWNXLibPINVOKE.CNWDomain_GetNameText(swigCPtr), true);
    return ret;
  }

  public CExoString GetDescriptionText() {
    CExoString ret = new CExoString(NWNXLibPINVOKE.CNWDomain_GetDescriptionText(swigCPtr), true);
    return ret;
  }

}

}
