//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public unsafe class CNWPlaceMeshManager : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CNWPlaceMeshManager(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CNWPlaceMeshManager obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CNWPlaceMeshManager() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NWNXLibPINVOKE.delete_CNWPlaceMeshManager(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }
/*@SWIG:/__w/NWN.Native/NWN.Native/nwnx/Plugins/SWIG/SWIG_DotNET/DotNETExtensions.i,1,SWIG_DOTNET_EXTENSIONS@*/
  public global::System.IntPtr Pointer {
    get {
      return swigCPtr.Handle;
    }
  }

  public static unsafe implicit operator void*(CNWPlaceMeshManager self) {
    return (void*)self.swigCPtr.Handle;
  }

  public static unsafe CNWPlaceMeshManager FromPointer(void* pointer, bool memoryOwn = false) {
    return pointer != null ? new CNWPlaceMeshManager((global::System.IntPtr)pointer, memoryOwn) : null;
  }

  public static CNWPlaceMeshManager FromPointer(global::System.IntPtr pointer, bool memoryOwn = false) {
    return pointer != global::System.IntPtr.Zero ? new CNWPlaceMeshManager(pointer, memoryOwn) : null;
  }

  public bool Equals(CNWPlaceMeshManager other) {
    if (ReferenceEquals(null, other)) {
      return false;
    }

    if (ReferenceEquals(this, other)) {
      return true;
    }

    return Pointer.Equals(other.Pointer);
  }

  public override bool Equals(object obj) {
    return ReferenceEquals(this, obj) || obj is CNWPlaceMeshManager other && Equals(other);
  }

  public override int GetHashCode() {
    return swigCPtr.Handle.GetHashCode();
  }

  public static bool operator ==(CNWPlaceMeshManager left, CNWPlaceMeshManager right) {
    return Equals(left, right);
  }

  public static bool operator !=(CNWPlaceMeshManager left, CNWPlaceMeshManager right) {
    return !Equals(left, right);
  }
/*@SWIG@*/
  public int m_nArraySize {
    set {
      NWNXLibPINVOKE.CNWPlaceMeshManager_m_nArraySize_set(swigCPtr, value);
    } 
    get {
      int retVal = NWNXLibPINVOKE.CNWPlaceMeshManager_m_nArraySize_get(swigCPtr);
      return retVal;
    }

  }

  public void** m_pSurfaceMeshLoaded {
    set {
      NWNXLibPINVOKE.CNWPlaceMeshManager_m_pSurfaceMeshLoaded_set(swigCPtr, (global::System.IntPtr)value);
    } 
    get {
        global::System.IntPtr retVal = NWNXLibPINVOKE.CNWPlaceMeshManager_m_pSurfaceMeshLoaded_get(swigCPtr);
        return (void**)retVal;
    }

  }

  public CNWPlaceMeshManager() : this(NWNXLibPINVOKE.new_CNWPlaceMeshManager(), true) {
  }

  public void InitializeWalkMeshes(int nSize) {
    NWNXLibPINVOKE.CNWPlaceMeshManager_InitializeWalkMeshes(swigCPtr, nSize);
  }

  public void ClearWalkMeshes() {
    NWNXLibPINVOKE.CNWPlaceMeshManager_ClearWalkMeshes(swigCPtr);
  }

  public CNWPlaceableSurfaceMesh GetWalkMesh(int nAppearanceType) {
    global::System.IntPtr cPtr = NWNXLibPINVOKE.CNWPlaceMeshManager_GetWalkMesh(swigCPtr, nAppearanceType);
    CNWPlaceableSurfaceMesh ret = (cPtr == global::System.IntPtr.Zero) ? null : new CNWPlaceableSurfaceMesh(cPtr, false);
    return ret;
  }

  public void _Destructor() {
    NWNXLibPINVOKE.CNWPlaceMeshManager__Destructor(swigCPtr);
  }

}

}
