//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public class CNWSInvitationDetails : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CNWSInvitationDetails(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CNWSInvitationDetails obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CNWSInvitationDetails() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint m_oidCreature {
    set {
      NWNXLibPINVOKE.CNWSInvitationDetails_m_oidCreature_set(swigCPtr, value);
    } 
    get {
      uint ret = NWNXLibPINVOKE.CNWSInvitationDetails_m_oidCreature_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_nCalenderDay {
    set {
      NWNXLibPINVOKE.CNWSInvitationDetails_m_nCalenderDay_set(swigCPtr, value);
    } 
    get {
      uint ret = NWNXLibPINVOKE.CNWSInvitationDetails_m_nCalenderDay_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_nTimeOfDay {
    set {
      NWNXLibPINVOKE.CNWSInvitationDetails_m_nTimeOfDay_set(swigCPtr, value);
    } 
    get {
      uint ret = NWNXLibPINVOKE.CNWSInvitationDetails_m_nTimeOfDay_get(swigCPtr);
      return ret;
    } 
  }

}

}
