//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public enum CombatMode {
  None = 0,
  Parry = 1,
  PowerAttack = 2,
  ImprovedPowerAttack = 3,
  CounterSpell = 4,
  FlurryOfBlows = 5,
  RapidShot = 6,
  Expertise = 7,
  ImprovedExpertise = 8,
  DefensiveCasting = 9,
  DirtyFighting = 10,
  DefensiveStance = 11
}

}
