//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public unsafe class CResRefArray : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CResRefArray(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CResRefArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CResRefArray() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NWNXLibPINVOKE.delete_CResRefArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }
/*@SWIG:/__w/NWN.Native/NWN.Native/nwnx/Plugins/SWIG/SWIG_DotNET/DotNETExtensions.i,1,SWIG_DOTNET_EXTENSIONS@*/
  public global::System.IntPtr Pointer {
    get {
      return swigCPtr.Handle;
    }
  }

  public static unsafe implicit operator void*(CResRefArray self) {
    return (void*)self.swigCPtr.Handle;
  }

  public static unsafe CResRefArray FromPointer(void* pointer, bool memoryOwn = false) {
    return pointer != null ? new CResRefArray((global::System.IntPtr)pointer, memoryOwn) : null;
  }

  public static CResRefArray FromPointer(global::System.IntPtr pointer, bool memoryOwn = false) {
    return pointer != global::System.IntPtr.Zero ? new CResRefArray(pointer, memoryOwn) : null;
  }

  public bool Equals(CResRefArray other) {
    if (ReferenceEquals(null, other)) {
      return false;
    }

    if (ReferenceEquals(this, other)) {
      return true;
    }

    return Pointer.Equals(other.Pointer);
  }

  public override bool Equals(object obj) {
    return ReferenceEquals(this, obj) || obj is CResRefArray other && Equals(other);
  }

  public override int GetHashCode() {
    return swigCPtr.Handle.GetHashCode();
  }

  public static bool operator ==(CResRefArray left, CResRefArray right) {
    return Equals(left, right);
  }

  public static bool operator !=(CResRefArray left, CResRefArray right) {
    return !Equals(left, right);
  }
/*@SWIG@*/

  public CResRef this[int index] {
    get {
      return GetItem(index);
    }
    set {
      SetItem(index, value);
    }
  }
  public CResRefArray(int nElements) : this(NWNXLibPINVOKE.new_CResRefArray(nElements), true) {
  }

  public CResRef GetItem(int index) {
    global::System.IntPtr cPtr = NWNXLibPINVOKE.CResRefArray_GetItem(swigCPtr, index);
    CResRef ret = (cPtr == global::System.IntPtr.Zero) ? null : new CResRef(cPtr, false);
    return ret;
  }

  public void SetItem(int index, CResRef value) {
    NWNXLibPINVOKE.CResRefArray_SetItem(swigCPtr, index, CResRef.getCPtr(value));
  }

  public static CResRefArray FromPointer(CResRef ptr) {
    global::System.IntPtr cPtr = NWNXLibPINVOKE.CResRefArray_FromPointer(CResRef.getCPtr(ptr));
    CResRefArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new CResRefArray(cPtr, false);
    return ret;
  }

}

}
