//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public unsafe class CScriptCompilerIncludeFileStackEntry : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CScriptCompilerIncludeFileStackEntry(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CScriptCompilerIncludeFileStackEntry obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CScriptCompilerIncludeFileStackEntry() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NWNXLibPINVOKE.delete_CScriptCompilerIncludeFileStackEntry(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }
/*@SWIG:/__w/NWN.Native/NWN.Native/nwnx/Plugins/SWIG/SWIG_DotNET/API_NWNXLib.i,25,SWIG_DOTNET_EXTENSIONS@*/
  public global::System.IntPtr Pointer {
    get {
      return swigCPtr.Handle;
    }
  }

  public static unsafe implicit operator void*(CScriptCompilerIncludeFileStackEntry self) {
    return (void*)self.swigCPtr.Handle;
  }

  public static unsafe CScriptCompilerIncludeFileStackEntry FromPointer(void* pointer, bool memoryOwn = false) {
    return pointer != null ? new CScriptCompilerIncludeFileStackEntry((global::System.IntPtr)pointer, memoryOwn) : null;
  }

  public static CScriptCompilerIncludeFileStackEntry FromPointer(global::System.IntPtr pointer, bool memoryOwn = false) {
    return pointer != global::System.IntPtr.Zero ? new CScriptCompilerIncludeFileStackEntry(pointer, memoryOwn) : null;
  }

  public bool Equals(CScriptCompilerIncludeFileStackEntry other) {
    if (ReferenceEquals(null, other)) {
      return false;
    }

    if (ReferenceEquals(this, other)) {
      return true;
    }

    return Pointer.Equals(other.Pointer);
  }

  public override bool Equals(object obj) {
    return ReferenceEquals(this, obj) || obj is CScriptCompilerIncludeFileStackEntry other && Equals(other);
  }

  public override int GetHashCode() {
    return swigCPtr.Handle.GetHashCode();
  }

  public static bool operator ==(CScriptCompilerIncludeFileStackEntry left, CScriptCompilerIncludeFileStackEntry right) {
    return Equals(left, right);
  }

  public static bool operator !=(CScriptCompilerIncludeFileStackEntry left, CScriptCompilerIncludeFileStackEntry right) {
    return !Equals(left, right);
  }
/*@SWIG@*/
  public CExoString m_sCompiledScriptName {
    set {
      NWNXLibPINVOKE.CScriptCompilerIncludeFileStackEntry_m_sCompiledScriptName_set(swigCPtr, CExoString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = NWNXLibPINVOKE.CScriptCompilerIncludeFileStackEntry_m_sCompiledScriptName_get(swigCPtr);
      CExoString ret = (cPtr == global::System.IntPtr.Zero) ? null : new CExoString(cPtr, false);
      return ret;
    } 
  }

  public CScriptSourceFile m_cSourceScript {
    set {
      NWNXLibPINVOKE.CScriptCompilerIncludeFileStackEntry_m_cSourceScript_set(swigCPtr, CScriptSourceFile.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = NWNXLibPINVOKE.CScriptCompilerIncludeFileStackEntry_m_cSourceScript_get(swigCPtr);
      CScriptSourceFile ret = (cPtr == global::System.IntPtr.Zero) ? null : new CScriptSourceFile(cPtr, false);
      return ret;
    } 
  }

  public int m_nLine {
    set {
      NWNXLibPINVOKE.CScriptCompilerIncludeFileStackEntry_m_nLine_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CScriptCompilerIncludeFileStackEntry_m_nLine_get(swigCPtr);
      return ret;
    } 
  }

  public int m_nCharacterOnLine {
    set {
      NWNXLibPINVOKE.CScriptCompilerIncludeFileStackEntry_m_nCharacterOnLine_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CScriptCompilerIncludeFileStackEntry_m_nCharacterOnLine_get(swigCPtr);
      return ret;
    } 
  }

  public int m_nTokenStatus {
    set {
      NWNXLibPINVOKE.CScriptCompilerIncludeFileStackEntry_m_nTokenStatus_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CScriptCompilerIncludeFileStackEntry_m_nTokenStatus_get(swigCPtr);
      return ret;
    } 
  }

  public int m_nTokenCharacters {
    set {
      NWNXLibPINVOKE.CScriptCompilerIncludeFileStackEntry_m_nTokenCharacters_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CScriptCompilerIncludeFileStackEntry_m_nTokenCharacters_get(swigCPtr);
      return ret;
    } 
  }

  public CScriptCompilerIncludeFileStackEntry() : this(NWNXLibPINVOKE.new_CScriptCompilerIncludeFileStackEntry(), true) {
  }

}

}
