//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public unsafe class CServerNetOptions : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public CServerNetOptions(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public CServerNetOptions(void* cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, (global::System.IntPtr)cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CServerNetOptions obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CServerNetOptions() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NWNXLibPINVOKE.delete_CServerNetOptions(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public System.IntPtr Pointer {
    get {
      return swigCPtr.Handle;
    }
  }

  public static unsafe implicit operator void*(CServerNetOptions self) {
    return (void*)self.swigCPtr.Handle;
  }

  public static implicit operator System.IntPtr(CServerNetOptions self) {
    return self.swigCPtr.Handle;
  }

  public bool Equals(CServerNetOptions other) {
    if (ReferenceEquals(null, other)) {
      return false;
    }

    if (ReferenceEquals(this, other)) {
      return true;
    }

    return Pointer.Equals(other.Pointer);
  }

  public override bool Equals(object obj) {
    return ReferenceEquals(this, obj) || obj is CServerNetOptions other && Equals(other);
  }

  public override int GetHashCode() {
    return swigCPtr.Handle.GetHashCode();
  }

  public static bool operator ==(CServerNetOptions left, CServerNetOptions right) {
    return Equals(left, right);
  }

  public static bool operator !=(CServerNetOptions left, CServerNetOptions right) {
    return !Equals(left, right);
  }

  public int m_nGameRegion {
    set {
      NWNXLibPINVOKE.CServerNetOptions_m_nGameRegion_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CServerNetOptions_m_nGameRegion_get(swigCPtr);
      return ret;
    } 
  }

  public CExoString m_szGameDetails {
    set {
      NWNXLibPINVOKE.CServerNetOptions_m_szGameDetails_set(swigCPtr, CExoString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = NWNXLibPINVOKE.CServerNetOptions_m_szGameDetails_get(swigCPtr);
      CExoString ret = (cPtr == global::System.IntPtr.Zero) ? null : new CExoString(cPtr, false);
      return ret;
    } 
  }

  public short m_GameType {
    set {
      NWNXLibPINVOKE.CServerNetOptions_m_GameType_set(swigCPtr, value);
    } 
    get {
      short ret = NWNXLibPINVOKE.CServerNetOptions_m_GameType_get(swigCPtr);
      return ret;
    } 
  }

  public int m_bNetworkRelaysEnabled {
    set {
      NWNXLibPINVOKE.CServerNetOptions_m_bNetworkRelaysEnabled_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CServerNetOptions_m_bNetworkRelaysEnabled_get(swigCPtr);
      return ret;
    } 
  }

  public CServerNetOptions() : this(NWNXLibPINVOKE.new_CServerNetOptions(), true) {
  }

}

}
