//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public class CWorldTimer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CWorldTimer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CWorldTimer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CWorldTimer() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NWNXLibPINVOKE.delete_CWorldTimer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int m_bFixedSnapshotRate {
    set {
      NWNXLibPINVOKE.CWorldTimer_m_bFixedSnapshotRate_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CWorldTimer_m_bFixedSnapshotRate_get(swigCPtr);
      return ret;
    } 
  }

  public int m_nFixedSnapshotsPerSecond {
    set {
      NWNXLibPINVOKE.CWorldTimer_m_nFixedSnapshotsPerSecond_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CWorldTimer_m_nFixedSnapshotsPerSecond_get(swigCPtr);
      return ret;
    } 
  }

  public ulong m_nTimeSnapshot {
    set {
      NWNXLibPINVOKE.CWorldTimer_m_nTimeSnapshot_set(swigCPtr, value);
    } 
    get {
      ulong ret = NWNXLibPINVOKE.CWorldTimer_m_nTimeSnapshot_get(swigCPtr);
      return ret;
    } 
  }

  public ulong m_nLastTimeSnapshot {
    set {
      NWNXLibPINVOKE.CWorldTimer_m_nLastTimeSnapshot_set(swigCPtr, value);
    } 
    get {
      ulong ret = NWNXLibPINVOKE.CWorldTimer_m_nLastTimeSnapshot_get(swigCPtr);
      return ret;
    } 
  }

  public int m_bPaused {
    set {
      NWNXLibPINVOKE.CWorldTimer_m_bPaused_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.CWorldTimer_m_bPaused_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_nPausedCalendarDay {
    set {
      NWNXLibPINVOKE.CWorldTimer_m_nPausedCalendarDay_set(swigCPtr, value);
    } 
    get {
      uint ret = NWNXLibPINVOKE.CWorldTimer_m_nPausedCalendarDay_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_nPausedTimeOfDay {
    set {
      NWNXLibPINVOKE.CWorldTimer_m_nPausedTimeOfDay_set(swigCPtr, value);
    } 
    get {
      uint ret = NWNXLibPINVOKE.CWorldTimer_m_nPausedTimeOfDay_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_nCalendarDayAdjustment {
    set {
      NWNXLibPINVOKE.CWorldTimer_m_nCalendarDayAdjustment_set(swigCPtr, value);
    } 
    get {
      uint ret = NWNXLibPINVOKE.CWorldTimer_m_nCalendarDayAdjustment_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_nTimeOfDayAdjustment {
    set {
      NWNXLibPINVOKE.CWorldTimer_m_nTimeOfDayAdjustment_set(swigCPtr, value);
    } 
    get {
      uint ret = NWNXLibPINVOKE.CWorldTimer_m_nTimeOfDayAdjustment_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_nMinutesPerHour {
    set {
      NWNXLibPINVOKE.CWorldTimer_m_nMinutesPerHour_set(swigCPtr, value);
    } 
    get {
      byte ret = NWNXLibPINVOKE.CWorldTimer_m_nMinutesPerHour_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_nMillisecondsPerDay {
    set {
      NWNXLibPINVOKE.CWorldTimer_m_nMillisecondsPerDay_set(swigCPtr, value);
    } 
    get {
      uint ret = NWNXLibPINVOKE.CWorldTimer_m_nMillisecondsPerDay_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_nSecondsPerDay {
    set {
      NWNXLibPINVOKE.CWorldTimer_m_nSecondsPerDay_set(swigCPtr, value);
    } 
    get {
      uint ret = NWNXLibPINVOKE.CWorldTimer_m_nSecondsPerDay_get(swigCPtr);
      return ret;
    } 
  }

  public CWorldTimer() : this(NWNXLibPINVOKE.new_CWorldTimer(), true) {
  }

  public void SetSnapshotTime() {
    NWNXLibPINVOKE.CWorldTimer_SetSnapshotTime(swigCPtr);
  }

  public ulong GetSnapshotTime() {
    ulong ret = NWNXLibPINVOKE.CWorldTimer_GetSnapshotTime(swigCPtr);
    return ret;
  }

  public ulong GetSnapshotTimeDifference() {
    ulong ret = NWNXLibPINVOKE.CWorldTimer_GetSnapshotTimeDifference(swigCPtr);
    return ret;
  }

  public uint ConvertToCalendarDay(uint nYear, uint nMonth, uint nDay) {
    uint ret = NWNXLibPINVOKE.CWorldTimer_ConvertToCalendarDay(swigCPtr, nYear, nMonth, nDay);
    return ret;
  }

  public uint ConvertToTimeOfDay(uint nHour, uint nMinute, uint nSecond, uint nMillisecond) {
    uint ret = NWNXLibPINVOKE.CWorldTimer_ConvertToTimeOfDay(swigCPtr, nHour, nMinute, nSecond, nMillisecond);
    return ret;
  }

  public void ConvertFromCalendarDay(uint nCalendarDay, SWIGTYPE_p_unsigned_int nYear, SWIGTYPE_p_unsigned_int nMonth, SWIGTYPE_p_unsigned_int nDay) {
    NWNXLibPINVOKE.CWorldTimer_ConvertFromCalendarDay(swigCPtr, nCalendarDay, SWIGTYPE_p_unsigned_int.getCPtr(nYear), SWIGTYPE_p_unsigned_int.getCPtr(nMonth), SWIGTYPE_p_unsigned_int.getCPtr(nDay));
  }

  public void ConvertFromTimeOfDay(uint nTimeOfDay, SWIGTYPE_p_unsigned_int nHour, SWIGTYPE_p_unsigned_int nMinute, SWIGTYPE_p_unsigned_int nSecond, SWIGTYPE_p_unsigned_int nMillisecond) {
    NWNXLibPINVOKE.CWorldTimer_ConvertFromTimeOfDay(swigCPtr, nTimeOfDay, SWIGTYPE_p_unsigned_int.getCPtr(nHour), SWIGTYPE_p_unsigned_int.getCPtr(nMinute), SWIGTYPE_p_unsigned_int.getCPtr(nSecond), SWIGTYPE_p_unsigned_int.getCPtr(nMillisecond));
  }

  public void SetWorldTime(uint nYear, uint nMonth, uint nDay, uint nHour, uint nMinute, uint nSecond, uint nMillisecond, int bTakeSnapshot) {
    NWNXLibPINVOKE.CWorldTimer_SetWorldTime__SWIG_0(swigCPtr, nYear, nMonth, nDay, nHour, nMinute, nSecond, nMillisecond, bTakeSnapshot);
  }

  public void SetWorldTime(uint nYear, uint nMonth, uint nDay, uint nHour, uint nMinute, uint nSecond, uint nMillisecond) {
    NWNXLibPINVOKE.CWorldTimer_SetWorldTime__SWIG_1(swigCPtr, nYear, nMonth, nDay, nHour, nMinute, nSecond, nMillisecond);
  }

  public void SetWorldTime(uint nCalendarDay, uint nTimeOfDay, int bTakeSnapshot) {
    NWNXLibPINVOKE.CWorldTimer_SetWorldTime__SWIG_2(swigCPtr, nCalendarDay, nTimeOfDay, bTakeSnapshot);
  }

  public void SetWorldTime(uint nCalendarDay, uint nTimeOfDay) {
    NWNXLibPINVOKE.CWorldTimer_SetWorldTime__SWIG_3(swigCPtr, nCalendarDay, nTimeOfDay);
  }

  public uint GetTimeDifferenceFromWorldTime(uint nCalendarDay, uint nTimeOfDay) {
    uint ret = NWNXLibPINVOKE.CWorldTimer_GetTimeDifferenceFromWorldTime(swigCPtr, nCalendarDay, nTimeOfDay);
    return ret;
  }

  public ulong GetTimeDifference(uint nCalendarDay1, uint nTimeOfDay1, uint nCalendarDay2, uint nTimeOfDay2) {
    ulong ret = NWNXLibPINVOKE.CWorldTimer_GetTimeDifference(swigCPtr, nCalendarDay1, nTimeOfDay1, nCalendarDay2, nTimeOfDay2);
    return ret;
  }

  public void GetWorldTime(SWIGTYPE_p_unsigned_int nCalendarDay, SWIGTYPE_p_unsigned_int nTimeOfDay) {
    NWNXLibPINVOKE.CWorldTimer_GetWorldTime(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(nCalendarDay), SWIGTYPE_p_unsigned_int.getCPtr(nTimeOfDay));
  }

  public uint AddWorldTimes(uint nCalendarDay1, uint nTimeOfDay1, uint nCalendarDay2, uint nTimeOfDay2, SWIGTYPE_p_unsigned_int nCalendarDayRes, SWIGTYPE_p_unsigned_int nTimeOfDayRes) {
    uint ret = NWNXLibPINVOKE.CWorldTimer_AddWorldTimes(swigCPtr, nCalendarDay1, nTimeOfDay1, nCalendarDay2, nTimeOfDay2, SWIGTYPE_p_unsigned_int.getCPtr(nCalendarDayRes), SWIGTYPE_p_unsigned_int.getCPtr(nTimeOfDayRes));
    return ret;
  }

  public uint SubtractWorldTimes(uint nCalendarDay1, uint nTimeOfDay1, uint nCalendarDay2, uint nTimeOfDay2, SWIGTYPE_p_unsigned_int nCalendarDayRes, SWIGTYPE_p_unsigned_int nTimeOfDayRes) {
    uint ret = NWNXLibPINVOKE.CWorldTimer_SubtractWorldTimes(swigCPtr, nCalendarDay1, nTimeOfDay1, nCalendarDay2, nTimeOfDay2, SWIGTYPE_p_unsigned_int.getCPtr(nCalendarDayRes), SWIGTYPE_p_unsigned_int.getCPtr(nTimeOfDayRes));
    return ret;
  }

  public int CompareWorldTimes(uint nCalendarDay1, uint nTimeOfDay1, uint nCalendarDay2, uint nTimeOfDay2) {
    int ret = NWNXLibPINVOKE.CWorldTimer_CompareWorldTimes(swigCPtr, nCalendarDay1, nTimeOfDay1, nCalendarDay2, nTimeOfDay2);
    return ret;
  }

  public void PauseWorldTimer() {
    NWNXLibPINVOKE.CWorldTimer_PauseWorldTimer(swigCPtr);
  }

  public void UnpauseWorldTimer() {
    NWNXLibPINVOKE.CWorldTimer_UnpauseWorldTimer(swigCPtr);
  }

  public uint GetWorldTimeCalendarDay() {
    uint ret = NWNXLibPINVOKE.CWorldTimer_GetWorldTimeCalendarDay(swigCPtr);
    return ret;
  }

  public CExoString GetWorldTimeCalendarDayString() {
    CExoString ret = new CExoString(NWNXLibPINVOKE.CWorldTimer_GetWorldTimeCalendarDayString(swigCPtr), true);
    return ret;
  }

  public uint GetWorldTimeTimeOfDay() {
    uint ret = NWNXLibPINVOKE.CWorldTimer_GetWorldTimeTimeOfDay(swigCPtr);
    return ret;
  }

  public CExoString GetWorldTimeTimeOfDayString() {
    CExoString ret = new CExoString(NWNXLibPINVOKE.CWorldTimer_GetWorldTimeTimeOfDayString(swigCPtr), true);
    return ret;
  }

  public CExoString TranslateWorldTimeToString(uint nCalendarDay, uint nTimeOfDay, CExoString sTranslatedDayString, CExoString sTranslatedMonthString) {
    CExoString ret = new CExoString(NWNXLibPINVOKE.CWorldTimer_TranslateWorldTimeToString(swigCPtr, nCalendarDay, nTimeOfDay, CExoString.getCPtr(sTranslatedDayString), CExoString.getCPtr(sTranslatedMonthString)), true);
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint GetWorldTimeYear() {
    uint ret = NWNXLibPINVOKE.CWorldTimer_GetWorldTimeYear(swigCPtr);
    return ret;
  }

  public uint GetWorldTimeMonth() {
    uint ret = NWNXLibPINVOKE.CWorldTimer_GetWorldTimeMonth(swigCPtr);
    return ret;
  }

  public uint GetWorldTimeDay() {
    uint ret = NWNXLibPINVOKE.CWorldTimer_GetWorldTimeDay(swigCPtr);
    return ret;
  }

  public uint GetWorldTimeHour() {
    uint ret = NWNXLibPINVOKE.CWorldTimer_GetWorldTimeHour(swigCPtr);
    return ret;
  }

  public uint GetWorldTimeMinute() {
    uint ret = NWNXLibPINVOKE.CWorldTimer_GetWorldTimeMinute(swigCPtr);
    return ret;
  }

  public uint GetWorldTimeSecond() {
    uint ret = NWNXLibPINVOKE.CWorldTimer_GetWorldTimeSecond(swigCPtr);
    return ret;
  }

  public uint GetWorldTimeMillisecond() {
    uint ret = NWNXLibPINVOKE.CWorldTimer_GetWorldTimeMillisecond(swigCPtr);
    return ret;
  }

  public void SetFixedSnapshotRate(int bActivate, int nSnapshotsPerSecond) {
    NWNXLibPINVOKE.CWorldTimer_SetFixedSnapshotRate(swigCPtr, bActivate, nSnapshotsPerSecond);
  }

  public uint GetCalendarDayFromSeconds(float fSeconds) {
    uint ret = NWNXLibPINVOKE.CWorldTimer_GetCalendarDayFromSeconds(swigCPtr, fSeconds);
    return ret;
  }

  public uint GetTimeOfDayFromSeconds(float fSeconds) {
    uint ret = NWNXLibPINVOKE.CWorldTimer_GetTimeOfDayFromSeconds(swigCPtr, fSeconds);
    return ret;
  }

  public void ResetTimer(CWorldTimer pTimer) {
    NWNXLibPINVOKE.CWorldTimer_ResetTimer(swigCPtr, CWorldTimer.getCPtr(pTimer));
  }

  public void SetMinutesPerHour(byte nMinutesPerHour) {
    NWNXLibPINVOKE.CWorldTimer_SetMinutesPerHour(swigCPtr, nMinutesPerHour);
  }

  public void AdvanceToTime(int nHour, int nMinute, int nSecond, int nMillisecond) {
    NWNXLibPINVOKE.CWorldTimer_AdvanceToTime(swigCPtr, nHour, nMinute, nSecond, nMillisecond);
  }

}

}
