//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public class IntendedConnectionData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IntendedConnectionData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IntendedConnectionData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IntendedConnectionData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public byte m_nConnectionType {
    set {
      NWNXLibPINVOKE.IntendedConnectionData_m_nConnectionType_set(swigCPtr, value);
    } 
    get {
      byte ret = NWNXLibPINVOKE.IntendedConnectionData_m_nConnectionType_get(swigCPtr);
      return ret;
    } 
  }

  public int m_nPlayerLanguage {
    set {
      NWNXLibPINVOKE.IntendedConnectionData_m_nPlayerLanguage_set(swigCPtr, value);
    } 
    get {
      int ret = NWNXLibPINVOKE.IntendedConnectionData_m_nPlayerLanguage_get(swigCPtr);
      return ret;
    } 
  }

  public CExoString m_sPlayerName {
    set {
      NWNXLibPINVOKE.IntendedConnectionData_m_sPlayerName_set(swigCPtr, CExoString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = NWNXLibPINVOKE.IntendedConnectionData_m_sPlayerName_get(swigCPtr);
      CExoString ret = (cPtr == global::System.IntPtr.Zero) ? null : new CExoString(cPtr, false);
      return ret;
    } 
  }

  public CExoString m_sCDKey {
    set {
      NWNXLibPINVOKE.IntendedConnectionData_m_sCDKey_set(swigCPtr, CExoString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = NWNXLibPINVOKE.IntendedConnectionData_m_sCDKey_get(swigCPtr);
      CExoString ret = (cPtr == global::System.IntPtr.Zero) ? null : new CExoString(cPtr, false);
      return ret;
    } 
  }

  public CExoString m_sLegacyCDKey {
    set {
      NWNXLibPINVOKE.IntendedConnectionData_m_sLegacyCDKey_set(swigCPtr, CExoString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = NWNXLibPINVOKE.IntendedConnectionData_m_sLegacyCDKey_get(swigCPtr);
      CExoString ret = (cPtr == global::System.IntPtr.Zero) ? null : new CExoString(cPtr, false);
      return ret;
    } 
  }

}

}
