//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public enum MessageInventoryMinor {
  Equip = 0x01,
  EquipCancel = 0x02,
  Drop = 0x03,
  DropCancel = 0x04,
  Pickup = 0x05,
  PickupCancel = 0x06,
  Unequip = 0x07,
  UnequipCancel = 0x08,
  RepositoryMove = 0x09,
  RepositoryMoveCancel = 0x0a,
  EquipToggle = 0x0b,
  Use = 0x0c,
  LearnScroll = 0x0d,
  LearnScrollSuccess = 0x0e,
  ConfirmDrop = 0x0f
}

}
