//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public enum MessagePVPMinor {
  ListAdd = 0x01,
  ListRemove = 0x02,
  AttitudeChange = 0x03,
  DifficultyChange = 0x04
}

}
