//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public enum MessageAmbientMinor {
  MusicPlay = 0x01,
  MusicSetDelay = 0x02,
  MusicChange = 0x03,
  BattleMusicPlay = 0x04,
  BattleMusicChange = 0x05,
  SoundPlay = 0x06,
  SoundChange = 0x07,
  SoundVolume = 0x08
}

}
