//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public class NWSyncAdvertisement : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public NWSyncAdvertisement(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NWSyncAdvertisement obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NWSyncAdvertisement() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public System.IntPtr Pointer {
    get {
      return swigCPtr.Handle;
    }
  }

  public bool Equals(NWSyncAdvertisement other) {
    if (ReferenceEquals(null, other)) {
      return false;
    }

    if (ReferenceEquals(this, other)) {
      return true;
    }

    return Pointer.Equals(other.Pointer);
  }

  public override bool Equals(object obj) {
    return ReferenceEquals(this, obj) || obj is NWSyncAdvertisement other && Equals(other);
  }

  public override int GetHashCode() {
    return swigCPtr.Handle.GetHashCode();
  }

  public static bool operator ==(NWSyncAdvertisement left, NWSyncAdvertisement right) {
    return Equals(left, right);
  }

  public static bool operator !=(NWSyncAdvertisement left, NWSyncAdvertisement right) {
    return !Equals(left, right);
  }

  public SHA1 m_primary_manifest {
    set {
      NWNXLibPINVOKE.NWSyncAdvertisement_m_primary_manifest_set(swigCPtr, SHA1.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = NWNXLibPINVOKE.NWSyncAdvertisement_m_primary_manifest_get(swigCPtr);
      SHA1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SHA1(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_NWSyncAdvertisementManifest_t m_additional_manifests {
    set {
      NWNXLibPINVOKE.NWSyncAdvertisement_m_additional_manifests_set(swigCPtr, SWIGTYPE_p_std__vectorT_NWSyncAdvertisementManifest_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = NWNXLibPINVOKE.NWSyncAdvertisement_m_additional_manifests_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_NWSyncAdvertisementManifest_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_NWSyncAdvertisementManifest_t(cPtr, false);
      return ret;
    } 
  }

  public CExoString m_url {
    set {
      NWNXLibPINVOKE.NWSyncAdvertisement_m_url_set(swigCPtr, CExoString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = NWNXLibPINVOKE.NWSyncAdvertisement_m_url_get(swigCPtr);
      CExoString ret = (cPtr == global::System.IntPtr.Zero) ? null : new CExoString(cPtr, false);
      return ret;
    } 
  }

}

}
