//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public enum ObjectType {
  GUI = 1,
  Tile = 2,
  Module = 3,
  Area = 4,
  Creature = 5,
  Item = 6,
  Trigger = 7,
  Projectile = 8,
  Placeable = 9,
  Door = 10,
  AreaOfEffect = 11,
  Waypoint = 12,
  Encounter = 13,
  Store = 14,
  Portal = 15,
  Sound = 16
}

}
