//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public class RESID : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RESID(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RESID obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RESID() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint m_resFileSource {
    set {
      NWNXLibPINVOKE.RESID_m_resFileSource_set(swigCPtr, value);
    } 
    get {
      uint ret = NWNXLibPINVOKE.RESID_m_resFileSource_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_resFileId {
    set {
      NWNXLibPINVOKE.RESID_m_resFileId_set(swigCPtr, value);
    } 
    get {
      uint ret = NWNXLibPINVOKE.RESID_m_resFileId_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_resTableId {
    set {
      NWNXLibPINVOKE.RESID_m_resTableId_set(swigCPtr, value);
    } 
    get {
      uint ret = NWNXLibPINVOKE.RESID_m_resTableId_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_resItemId {
    set {
      NWNXLibPINVOKE.RESID_m_resItemId_set(swigCPtr, value);
    } 
    get {
      uint ret = NWNXLibPINVOKE.RESID_m_resItemId_get(swigCPtr);
      return ret;
    } 
  }

}

}
