//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public unsafe class VectorNWSQLiteMigrationsDefinitionMigrationDef : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<Definition.MigrationDef>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorNWSQLiteMigrationsDefinitionMigrationDef(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorNWSQLiteMigrationsDefinitionMigrationDef obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VectorNWSQLiteMigrationsDefinitionMigrationDef() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NWNXLibPINVOKE.delete_VectorNWSQLiteMigrationsDefinitionMigrationDef(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public global::System.IntPtr Pointer {
    get {
      return swigCPtr.Handle;
    }
  }

  public static unsafe implicit operator void*(VectorNWSQLiteMigrationsDefinitionMigrationDef self) {
    return (void*)self.swigCPtr.Handle;
  }

  public static unsafe VectorNWSQLiteMigrationsDefinitionMigrationDef FromPointer(void* pointer, bool memoryOwn = false) {
    return pointer != null ? new VectorNWSQLiteMigrationsDefinitionMigrationDef((global::System.IntPtr)pointer, memoryOwn) : null;
  }

  public static VectorNWSQLiteMigrationsDefinitionMigrationDef FromPointer(global::System.IntPtr pointer, bool memoryOwn = false) {
    return pointer != global::System.IntPtr.Zero ? new VectorNWSQLiteMigrationsDefinitionMigrationDef(pointer, memoryOwn) : null;
  }

  public bool Equals(VectorNWSQLiteMigrationsDefinitionMigrationDef other) {
    if (ReferenceEquals(null, other)) {
      return false;
    }

    if (ReferenceEquals(this, other)) {
      return true;
    }

    return Pointer.Equals(other.Pointer);
  }

  public override bool Equals(object obj) {
    return ReferenceEquals(this, obj) || obj is VectorNWSQLiteMigrationsDefinitionMigrationDef other && Equals(other);
  }

  public override int GetHashCode() {
    return swigCPtr.Handle.GetHashCode();
  }

  public static bool operator ==(VectorNWSQLiteMigrationsDefinitionMigrationDef left, VectorNWSQLiteMigrationsDefinitionMigrationDef right) {
    return Equals(left, right);
  }

  public static bool operator !=(VectorNWSQLiteMigrationsDefinitionMigrationDef left, VectorNWSQLiteMigrationsDefinitionMigrationDef right) {
    return !Equals(left, right);
  }

  public VectorNWSQLiteMigrationsDefinitionMigrationDef(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Definition.MigrationDef element in c) {
      this.Add(element);
    }
  }

  public VectorNWSQLiteMigrationsDefinitionMigrationDef(global::System.Collections.Generic.IEnumerable<Definition.MigrationDef> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Definition.MigrationDef element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Definition.MigrationDef this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Definition.MigrationDef[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Definition.MigrationDef[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Definition.MigrationDef[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public Definition.MigrationDef[] ToArray() {
    Definition.MigrationDef[] array = new Definition.MigrationDef[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<Definition.MigrationDef> global::System.Collections.Generic.IEnumerable<Definition.MigrationDef>.GetEnumerator() {
    return new VectorNWSQLiteMigrationsDefinitionMigrationDefEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorNWSQLiteMigrationsDefinitionMigrationDefEnumerator(this);
  }

  public VectorNWSQLiteMigrationsDefinitionMigrationDefEnumerator GetEnumerator() {
    return new VectorNWSQLiteMigrationsDefinitionMigrationDefEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorNWSQLiteMigrationsDefinitionMigrationDefEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Definition.MigrationDef>
  {
    private VectorNWSQLiteMigrationsDefinitionMigrationDef collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorNWSQLiteMigrationsDefinitionMigrationDefEnumerator(VectorNWSQLiteMigrationsDefinitionMigrationDef collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Definition.MigrationDef Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Definition.MigrationDef)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_Clear(swigCPtr);
  }

  public void Add(Definition.MigrationDef x) {
    NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_Add(swigCPtr, Definition.MigrationDef.getCPtr(x));
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_reserve(swigCPtr, n);
  }

  public VectorNWSQLiteMigrationsDefinitionMigrationDef() : this(NWNXLibPINVOKE.new_VectorNWSQLiteMigrationsDefinitionMigrationDef__SWIG_0(), true) {
  }

  public VectorNWSQLiteMigrationsDefinitionMigrationDef(VectorNWSQLiteMigrationsDefinitionMigrationDef other) : this(NWNXLibPINVOKE.new_VectorNWSQLiteMigrationsDefinitionMigrationDef__SWIG_1(VectorNWSQLiteMigrationsDefinitionMigrationDef.getCPtr(other)), true) {
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorNWSQLiteMigrationsDefinitionMigrationDef(int capacity) : this(NWNXLibPINVOKE.new_VectorNWSQLiteMigrationsDefinitionMigrationDef__SWIG_2(capacity), true) {
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  private Definition.MigrationDef getitemcopy(int index) {
    Definition.MigrationDef ret = new Definition.MigrationDef(NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_getitemcopy(swigCPtr, index), true);
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Definition.MigrationDef getitem(int index) {
    Definition.MigrationDef ret = new Definition.MigrationDef(NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_getitem(swigCPtr, index), false);
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Definition.MigrationDef val) {
    NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_setitem(swigCPtr, index, Definition.MigrationDef.getCPtr(val));
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorNWSQLiteMigrationsDefinitionMigrationDef values) {
    NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_AddRange(swigCPtr, VectorNWSQLiteMigrationsDefinitionMigrationDef.getCPtr(values));
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorNWSQLiteMigrationsDefinitionMigrationDef GetRange(int index, int count) {
    global::System.IntPtr cPtr = NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_GetRange(swigCPtr, index, count);
    VectorNWSQLiteMigrationsDefinitionMigrationDef ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorNWSQLiteMigrationsDefinitionMigrationDef(cPtr, true);
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Definition.MigrationDef x) {
    NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_Insert(swigCPtr, index, Definition.MigrationDef.getCPtr(x));
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorNWSQLiteMigrationsDefinitionMigrationDef values) {
    NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_InsertRange(swigCPtr, index, VectorNWSQLiteMigrationsDefinitionMigrationDef.getCPtr(values));
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_RemoveAt(swigCPtr, index);
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_RemoveRange(swigCPtr, index, count);
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorNWSQLiteMigrationsDefinitionMigrationDef Repeat(Definition.MigrationDef value, int count) {
    global::System.IntPtr cPtr = NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_Repeat(Definition.MigrationDef.getCPtr(value), count);
    VectorNWSQLiteMigrationsDefinitionMigrationDef ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorNWSQLiteMigrationsDefinitionMigrationDef(cPtr, true);
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_Reverse__SWIG_1(swigCPtr, index, count);
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorNWSQLiteMigrationsDefinitionMigrationDef values) {
    NWNXLibPINVOKE.VectorNWSQLiteMigrationsDefinitionMigrationDef_SetRange(swigCPtr, index, VectorNWSQLiteMigrationsDefinitionMigrationDef.getCPtr(values));
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
