//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public unsafe class CExoArrayListCNWSPlayerPtr : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<CNWSPlayer>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CExoArrayListCNWSPlayerPtr(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CExoArrayListCNWSPlayerPtr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CExoArrayListCNWSPlayerPtr() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NWNXLibPINVOKE.delete_CExoArrayListCNWSPlayerPtr(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public global::System.IntPtr Pointer {
    get {
      return swigCPtr.Handle;
    }
  }

  public static unsafe implicit operator void*(CExoArrayListCNWSPlayerPtr self) {
    return (void*)self.swigCPtr.Handle;
  }

  public static unsafe CExoArrayListCNWSPlayerPtr FromPointer(void* pointer, bool memoryOwn = false) {
    return pointer != null ? new CExoArrayListCNWSPlayerPtr((global::System.IntPtr)pointer, memoryOwn) : null;
  }

  public static CExoArrayListCNWSPlayerPtr FromPointer(global::System.IntPtr pointer, bool memoryOwn = false) {
    return pointer != global::System.IntPtr.Zero ? new CExoArrayListCNWSPlayerPtr(pointer, memoryOwn) : null;
  }

  public bool Equals(CExoArrayListCNWSPlayerPtr other) {
    if (ReferenceEquals(null, other)) {
      return false;
    }

    if (ReferenceEquals(this, other)) {
      return true;
    }

    return Pointer.Equals(other.Pointer);
  }

  public override bool Equals(object obj) {
    return ReferenceEquals(this, obj) || obj is CExoArrayListCNWSPlayerPtr other && Equals(other);
  }

  public override int GetHashCode() {
    return swigCPtr.Handle.GetHashCode();
  }

  public static bool operator ==(CExoArrayListCNWSPlayerPtr left, CExoArrayListCNWSPlayerPtr right) {
    return Equals(left, right);
  }

  public static bool operator !=(CExoArrayListCNWSPlayerPtr left, CExoArrayListCNWSPlayerPtr right) {
    return !Equals(left, right);
  }

  public CExoArrayListCNWSPlayerPtr(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (CNWSPlayer element in c) {
      this.Add(element);
    }
  }

  public CExoArrayListCNWSPlayerPtr(global::System.Collections.Generic.IEnumerable<CNWSPlayer> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (CNWSPlayer element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public CNWSPlayer this[int index] {
    get {
      return InternalGetItem(index);
    }
    set {
      InternalSetItem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)array_size;
    }
    set {
      if (value < num)
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      SetSize(value);
    }
  }

  public int Count {
    get {
      return (int)num;
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(CNWSPlayer[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(CNWSPlayer[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void Clear()
  {
    SetSize(0);
  }

  public void CopyTo(int index, CNWSPlayer[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(InternalGetItemCopy(index+i), arrayIndex+i);
  }

  public CNWSPlayer[] ToArray() {
    CNWSPlayer[] array = new CNWSPlayer[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<CNWSPlayer> global::System.Collections.Generic.IEnumerable<CNWSPlayer>.GetEnumerator() {
    return new CExoArrayListCNWSPlayerPtrEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new CExoArrayListCNWSPlayerPtrEnumerator(this);
  }

  public CExoArrayListCNWSPlayerPtrEnumerator GetEnumerator() {
    return new CExoArrayListCNWSPlayerPtrEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class CExoArrayListCNWSPlayerPtrEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<CNWSPlayer>
  {
    private CExoArrayListCNWSPlayerPtr collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public CExoArrayListCNWSPlayerPtrEnumerator(CExoArrayListCNWSPlayerPtr collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public CNWSPlayer Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (CNWSPlayer)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  private int num {
    set {
      NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_num_set(swigCPtr, value);
    } 
    get {
      int retVal = NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_num_get(swigCPtr);
      return retVal;
    }

  }

  private int array_size {
    set {
      NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_array_size_set(swigCPtr, value);
    } 
    get {
      int retVal = NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_array_size_get(swigCPtr);
      return retVal;
    }

  }

  public void Add(CNWSPlayer t) {
    NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_Add(swigCPtr, CNWSPlayer.getCPtr(t));
  }

  public void Pack() {
    NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_Pack(swigCPtr);
  }

  private void Allocate(int s) {
    NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_Allocate(swigCPtr, s);
  }

  public void SetSize(int s) {
    NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_SetSize(swigCPtr, s);
  }

  public CExoArrayListCNWSPlayerPtr(int s) : this(NWNXLibPINVOKE.new_CExoArrayListCNWSPlayerPtr__SWIG_0(s), true) {
  }

  public CExoArrayListCNWSPlayerPtr() : this(NWNXLibPINVOKE.new_CExoArrayListCNWSPlayerPtr__SWIG_1(), true) {
  }

  public CExoArrayListCNWSPlayerPtr(CExoArrayListCNWSPlayerPtr list) : this(NWNXLibPINVOKE.new_CExoArrayListCNWSPlayerPtr__SWIG_2(CExoArrayListCNWSPlayerPtr.getCPtr(list)), true) {
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_RemoveAt(swigCPtr, index);
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public int IndexOf(CNWSPlayer t) {
    int retVal = NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_IndexOf(swigCPtr, CNWSPlayer.getCPtr(t));
    return retVal;
  }

  public int AddUnique(CNWSPlayer t) {
    int retVal = NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_AddUnique(swigCPtr, CNWSPlayer.getCPtr(t));
    return retVal;
  }

  private CNWSPlayer InternalGetItem(int index) {
    global::System.IntPtr cPtr = NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_InternalGetItem(swigCPtr, index);
    CNWSPlayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new CNWSPlayer(cPtr, false);
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private CNWSPlayer InternalGetItemCopy(int index) {
    global::System.IntPtr cPtr = NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_InternalGetItemCopy(swigCPtr, index);
    CNWSPlayer ret = (cPtr == global::System.IntPtr.Zero) ? null : new CNWSPlayer(cPtr, false);
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void InternalSetItem(int index, CNWSPlayer val) {
    NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_InternalSetItem(swigCPtr, index, CNWSPlayer.getCPtr(val));
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Insert(int index, CNWSPlayer x) {
    NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_Insert(swigCPtr, index, CNWSPlayer.getCPtr(x));
    if (NWNXLibPINVOKE.SWIGPendingException.Pending) throw NWNXLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(CNWSPlayer value) {
    bool ret = NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_Contains(swigCPtr, CNWSPlayer.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(CNWSPlayer value) {
    int retVal = NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_LastIndexOf(swigCPtr, CNWSPlayer.getCPtr(value));
    return retVal;
  }

  public bool Remove(CNWSPlayer value) {
    bool ret = NWNXLibPINVOKE.CExoArrayListCNWSPlayerPtr_Remove(swigCPtr, CNWSPlayer.getCPtr(value));
    return ret;
  }

}

}
