//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public enum ItemVFX {
  None = 0,
  Acid = 1,
  Cold = 2,
  Electrical = 3,
  Fire = 4,
  Sonic = 5,
  Holy = 6,
  Evil = 7
}

}
