//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public enum MessageCutsceneMinor {
  Status = 0x01,
  Cancel = 0x02,
  FadeToBlack = 0x03,
  FadeFromBlack = 0x04,
  StopFade = 0x05,
  BlackScreen = 0x06,
  HideGui = 0x07
}

}
