//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NWN.Native.API {

public enum QuickbarType {
  Empty = 0,
  Item = 1,
  Spell = 2,
  Skill = 3,
  Feat = 4,
  Script = 5,
  Dialog = 6,
  Attack = 7,
  Emote = 8,
  ItemPropertyCastspell = 9,
  ModeToggle = 10,
  DMCreateCreature = 11,
  DMCreateItem = 12,
  DMCreateEncounter = 13,
  DMCreateWaypoint = 14,
  DMCreateTrigger = 15,
  DMCreatePortal = 16,
  DMCreatePlaceable = 17,
  CommandLine = 18,
  DMMakeInvulnerable = 19,
  DMForceRest = 20,
  DMGoto = 21,
  DMHeal = 22,
  DMKill = 23,
  DMPossess = 24,
  DMImpersonate = 25,
  DMGiveGold = 27,
  DMTakeGold = 28,
  DMGiveItem = 29,
  DMTakeItem = 30,
  DMGiveXP = 31,
  DMTakeXP = 32,
  DMGiveLevel = 33,
  DMTakeLevel = 34,
  DMLimbo = 35,
  DMToggleAI = 36,
  RollDie = 37,
  PossessFamiliar = 38,
  AssociateCommand = 39,
  Examine = 40,
  Barter = 41,
  QuickChat = 42,
  CancelPolymorph = 43,
  SpellLikeAbility = 44,
  DMGiveGood = 45,
  DMGiveEvil = 46,
  DMGiveLawful = 47,
  DMGiveChaotic = 48
}

}
